- hosts: local
  connection: local
  tasks:
    - name : deploy
      local_action: command sudo cp -r ../unifest /Library/WebServer/Documents

- hosts: ec2
  remote_user: ubuntu
  sudo: yes
  tasks:
    - name: deploy
      action: synchronize src=../unifest dest=/var/www/html/ mode=755