#!/bin/bash

INSTANCE_ID=
TAG=

function main() {
	curr_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
	. $curr_dir/ec2.config
	ec2-create-tags $INSTANCE_ID --tag $TAG
	return 0
}


ok=1
while getopts i:t: opt; do
	case $opt in
		i) INSTANCE_ID=$OPTARG;;
		t) TAG=$OPTARG;;
		\?) echo "Invalid option: -$opt"; echo "Usage ec2-tag [-it]"; ok=0;;
	esac
done


if [ "$ok" = "1" ]; then
	main
fi